- recipe/meta.yaml
Checklist
Please don't merge yet :)
> fix osx recipe test

- recipe/bld.bat
- recipe/meta.yaml
> fixup windows build

- recipe/meta.yaml
> update libsolv to latest master

- recipe/meta.yaml
> fix recipe

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/win_.yaml
- README.md
- recipe/0001-de-prioritize-track_features-conda.patch
- recipe/meta.yaml
> Add patch to de-prioritize features

- .github/CODEOWNERS
- README.md
- recipe/0001-de-prioritize-track_features-conda.patch
- recipe/meta.yaml
Checklist
@conda-forge-admin, please rerender
> Add patch for new-style conda packages

- recipe/0001-de-prioritize-track_features-conda.patch
- recipe/meta.yaml
> Conda track features

- recipe/0002-win32-shared.patch
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
> enable shared library builds on windows

- recipe/export_solv_version_win.patch
- recipe/meta.yaml
> export libsolv version on win

- recipe/export_solv_version_win.patch
- recipe/meta.yaml
> fix installation of config.h on win

- recipe/enable_subprio_comparison.patch
- recipe/meta.yaml
> enable subprio comparison

- README.md
- recipe/build.sh
- recipe/install.sh
- recipe/meta.yaml
> Add static package

- recipe/fix_startswith_pep404.patch
- recipe/meta.yaml
> fix startswith with pep404 through patch

- recipe/meta.yaml
> Rebuild with new osx-arm64 zlib

- .ci_support/osx_arm64_.yaml
- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- LICENSE.txt
- README.md
- recipe/fix-win32-regex.patch
- recipe/meta.yaml
- recipe/use-only-tar-bz2.patch
From https://github.com/openSUSE/libsolv/pull/436
Checklist
> Add fix-win32-regex patch

- .azure-pipelines/azure-pipelines-linux.yml
- recipe/conda_variant_priorization.patch
- recipe/meta.yaml
> add new variant priorization patch

- .github/CODEOWNERS
- README.md
- recipe/add_strict_repo_prio_rule.patch
- recipe/meta.yaml
> Fix strict channel prio

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .github/CODEOWNERS
- README.md
- recipe/bld.bat
- recipe/conda_build_config.yaml
- recipe/meta.yaml
> Win static

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- .scripts/run_osx_build.sh
- recipe/bld.bat
- recipe/meta.yaml
- recipe/no_error_subdir_mismatch.patch
> Reset dev to main

- README.md
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
- recipe/test/CMakeLists.txt
- recipe/test/test.c
Checklist
The following refactor has successfully been tested in the dev channel `conda-forge/label/libsolv_dev::libsolv 0.7.24 *_6`:
- In mamba https://github.com/mamba-org/mamba/pull/2780 
- In micromamba-feedstock https://github.com/conda-forge/micromamba-feedstock/pull/140
> Refactor tests, win, and static builds

- .ci_support/linux_64_.yaml
- .ci_support/linux_aarch64_.yaml
- .ci_support/linux_ppc64le_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
> Add missing run_exports

- recipe/meta.yaml
> Rebuild 0.7.31

- recipe/meta.yaml
Checklist
@conda-forge-admin, please rerender
> Require the same patch version at runtime
